### ISSUE TITLE
div not closing properly even with proper indentation while using loops and conditions.

### ISSUE THREAD

**Issue by aavrug** [Talesoft/tale-jade#103]

**Comment by zorca** [comment]
Give a code example, pls.

**Comment by aavrug** [comment]
In sublime after making an enter it just got an space and because of that it was behaving like that. After using tab it is working fine.

**Comment by TorbenKoehn** [comment]
You can indent with either tabs or spaces.

Just make sure that you don't mix them (and even that works in most cases) and that you always have the same amount of spaces for each level (Don't indent level 1 with 2 spaces and then, suddenly, level 2 more lines below with 4 spaces)

Closing this. If you have further complications, please open a new issue :)
