### ISSUE TITLE
Escaping sequences possible bug

### ISSUE THREAD

**Issue by strobox** [Talesoft/tale-jade#105]
It's looks lie following line in jade:

`script#stylmock(data-items='globals' data-project='wdg_inv_2016_olya' data-save_path='c:\\Apache24\\htdocs\\romero\\wdg\\wdg_html\\wp-content\\themes\\invite2016\\styles.css')`

Renders to wrong html:

`<script id="stylmock" data-items="globals" data-project="wdg_inv_2016_olya" data-save_path="c:\\Apache24\\htdocs\
omero\\wdg\\wdg_html\\wp-content\   hemes\\invite2016\\styles.css"></script>`

Where `save_path` attribute contains evaluate escape sequences \r and \t which sholdn't happen I think.

**Comment by TorbenKoehn** [comment]
I guess I am missing a `\\` escape sequence. I'll take a look at this, thank you :)

**Comment by TorbenKoehn** [comment]
Meanwhile, as a quick-fix, put the value in a variable and put that in

``` jade
$save_path='c:\\Apache24\\htdocs\\romero\\wdg\\wdg_html\\wp-content\\themes\\invite2016\\styles.css'
script(data-save_path=$save_path)
```

That should work

**Comment by strobox** [comment]
Yes, good idea! Thank you!

**Comment by TorbenKoehn** [comment]
Is this fixed for you?
