### ISSUE TITLE
Hyperlinks are not displaying correctly

### ISSUE THREAD

**Issue by vnddr** [Talesoft/tale-jade#106]
Looks like one of the last commits broke something with hyperlinks. Link elements started to get their DOM parents’ classes. Some interface details like avatars (which are the links to the profile) started to appear different and changed their location. The problem showed up in https://github.com/Talesoft/tale-jade/commit/c73aa60fef6e3ca1b18aa5dde434fec39618de7f.

**Comment by TorbenKoehn** [comment]
This probably happened in f8e765f83d4b1d2318d4811681a434f02fa30b4b

I changed the whitespace handling, it didn't match official Jade's.

Can you give me some examples or screenshots?

If you e.g. use icons and they are dislocated, you probably had something like

``` jade
a(href='#')
    i.fa.fa-fw.fa-gear
    | Some text
```

which automatically added a whitespace between the icon and the text.

It doesn't do this anymore, but you can use multiple whitespaces (only the first one is ignored now)

``` jade
a(href='#')
    i.fa.fa-fw.fa-gear
    |  Some text
```

to get the same effect (Notice that `Some` has two whitespaces in front of it)

**Comment by TorbenKoehn** [comment]
Any update on this?

**Comment by TorbenKoehn** [comment]
I'll close this. If you have any further questions, re-open it please.
