### ISSUE TITLE
Syntax errors are hard to debug

### ISSUE THREAD

**Issue by ponychicken** [Talesoft/tale-jade#108]
Just received this: 
`Tale\Jade\Parser\Exception: Failed to parse Jade: The import instruction can't have children (indent at 5:2) in /Volumes/Leo/kirbysites/site/plugins/jade/vendor/talesoft/tale-jade/Parser.php on line 1199`

It would be nice if errors always said which jade file caused the error and where..

**Comment by TorbenKoehn** [comment]
Can you give me the stacktrace of that one?

I'll try to improve this.

**Comment by ponychicken** [comment]
![screenshot 2016-06-28 13 04 19](https://cloud.githubusercontent.com/assets/183302/16413199/dcbb7786-3d30-11e6-9440-160a7626a6ab.png)

**Comment by TorbenKoehn** [comment]
Okay

Well, the error itself seems to occur on an `include` or `extends` statement (Both are seen as `imports` by the Tale Jade engine). Make sure that those don't have any kind of child element or a sibling element that's indented too far (Mixing tabs and spaces may also create this error)

I can't tell you, which file it is, sadly, I'll improve error reporting further :)

**Comment by TorbenKoehn** [comment]
I improved error handling and re-wrote most error messages.

If you find something that doesn't show errors detailed enough, re-open this issue please :)
