### ISSUE TITLE
Block Expansion doesn't work with classes?

### ISSUE THREAD

**Issue by YamiOdymel** [Talesoft/tale-jade#112]
Tale-Jade

```
.a.b: .c.d
    | Hello, world!
```

Compiles

```
<div class="a b">
  c.d| Hello, world!
</div>
```

Maybe the dots made compiler escaped the classes?

I mean some thing like `p.` so we don't have to type `|` that thing?

**Comment by TorbenKoehn** [comment]
Wow, I did not notice haha

Well, right now just use `.a.b: div.c.d` (`div` is always the default tag [configurable])

Normally `.` doesnt kick in after a block expansion, but here it seems it does for some reason. I'll check it out.

You can assume that I'll fix the open stuff here this weekend.

**Comment by TorbenKoehn** [comment]
This, too, should be fixed in the recent commit. Please pull *@dev and tell me if it works.

**Comment by YamiOdymel** [comment]
And this works also.

### Tale Jade

```
.ts.-abc.-def.-gh-ij.--kl.mn.-op
    .q.r: .s.t
        .u.v: .wx-.yz.-ab.--cd.e
            .f.g: button.h.i.-jkl.--mn
                | Hello, World
```

### Outputed

```
<div class="ts -abc -def -gh-ij --kl mn -op">
    <div class="q r">
        <div class="s t">
            <div class="u v">
                <div class="wx- yz -ab --cd e">
                    <div class="f g">
                        <button class="h i -jkl --mn">
                            Hello, World
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
```
