### ISSUE TITLE
Your site is down

### ISSUE THREAD

**Issue by josegonzalez** [Talesoft/tale-jade#117]
It is giving me a 404 on github pages.

**Comment by TorbenKoehn** [comment]
Yup, that's why I updated the README recently.

The new page is located at http://jade.talesoft.codes/
The sandbox can be found at http://sandbox.jade.talesoft.codes/
My blog is located at http://torbens.talesoft.codes

**Comment by josegonzalez** [comment]
It's still in the description of the repo at the top here: https://cl.ly/0D0p2R2b2q1b

**Comment by TorbenKoehn** [comment]
Ah, overlooked that. Thank you, it's changed :)
