### ISSUE TITLE
Unescaped html strings

### ISSUE THREAD

**Issue by ArSharlahy** [Talesoft/tale-jade#120]
Syntax construction !{} and !=  seems not work, strings inserted by this methods still escaped.

**Comment by YamiOdymel** [comment]
Could you please show us your code :D  

It's working fine, perhaps you escaped it already before you output it?

**Comment by ArSharlahy** [comment]
It's very confusing but i'm just realised that i edit wrong mixin and issue does not exist.) Sorry))
