### ISSUE TITLE
Request for repo name update

### ISSUE THREAD

**Issue by elquimista** [Talesoft/tale-jade#129]
Hi @TorbenKoehn long time no see. Since Jade is renamed to Pug, isn't it time to reflect the change accordingly?

**Comment by TorbenKoehn** [comment]
Hello,


Tale Jade will be succeeded by Phug soon (https://github.com/phug-php)


Phug is a collaboration project of all popular, existing Jade implementations for PHP. We're aiming to make Jade/Pug the next big template engine in the PHP world.


Stay tuned :)


Thanks for your hint, anyways, I appreciate it.


Have a great day!

**Comment by elquimista** [comment]
Ok thanks for the info. I didn't know about `phug` project.

**Comment by elquimista** [comment]
P.S. so you're not actively maintaining this tale-jade project?

**Comment by TorbenKoehn** [comment]
It won’t be extended, but I will fix critical bugs when reported and I can handle it time-wise.

This library is actively maintained, responses will never take a long time :)

**Comment by elquimista** [comment]
Awesome! Truly appreciate your dedication to OSS.
