### ISSUE TITLE
Inconsistent unbuffered code

### ISSUE THREAD

**Issue by jacmoe** [Talesoft/tale-jade#18]
First of all: thanks for making this library!

I am fully aware that it is wet paint, but I've decided to take the plunge - after examining the alternatives - and integrate this with Yii2.

It really threw me for a loop, when I discovered - after many cryptic error messages - that I should not prepend conditional php code with the dash:

``` php
if $something
  ..
```

If would be better, and more consistent, to let that be unbuffered code:

``` php
- if $something
  ..
```

or

``` php
-if $something
  ..
```

If it threw me, it would probably trip someone else up as well. :)

**Comment by jacmoe** [comment]
D'oh - okay, so the very first page on Jadejs has an example where the conditionals are just written out..
So, that means that Tale Jade for PHP is closer to Jade than most - if not all other - php 'engines'. :)

However ->

> Jade's first-class conditional syntax allows for optional parenthesis, and you may now omit the leading -

And if Tale Jade dies with a horrible error message when you do prepend it with a dash.
It shouldn't. :)

**Comment by TorbenKoehn** [comment]
Hello @jacmoe, thank you for your feedback!

You can use both condition-styles, prefixed with `-` or not. In any case, using the non-prefixed style requires use to handle brackets yourself

``` jade
- if ($something):
    p Do something
- endif
```

or

``` jade
- if ($something) {
     p Do something
- }
```

The normal Jade-syntax introduces `if` and `unless` as normal Jade nodes

``` jade
if $something
    p Do something

unless $something
    p Do something
```

You can use any expression after the `if`. If your expression contains a `:` (e.g. ternary operator), you should put the condition in brackets

``` jade
if (empty($something) ? $somethingElse : $something)
    p Do something

```

Please tell me if you have any more questions regarding this :)

**Comment by jacmoe** [comment]
I will test this again. Thanks :)

**Comment by jacmoe** [comment]
Tale Jade seems to be treating the conditioned block as code if using the dash.

This works:

``` php
      if ($view->title == 'Login')
        p Hi there
      else
        p whoops
```

This, however, does not:

``` php
      -if ($view->title == 'Login')
        p Hi there
      -else
        p whoops
```

Jade complains: `syntax error, unexpected 'Hi' (T_STRING)|`

**Comment by jacmoe** [comment]
Generated code for the first:

``` php
      <?php if ($view->title == 'Login') {?>
        <p>
          Hi there
        </p>
      <?php }
       else {?>
        <p>
          whoops
        </p>
      <?php }?>
```

Other than a harmless stray php pair of tags, it is fine.

Generated code for the second:

``` php
      <?php if ($view->title == 'Login')
        p Hi there
      ?>
      <?php else
        p whoops
      ?>
```

Seems like a different kind of logic is at play here :)

**Comment by TorbenKoehn** [comment]
Oh man, I'm sorry, I lied to you hahaha

`-` creates a code-block and everything indented inside it will also be in the code block.

This tries to reflect the official version:
http://jade-lang.com/reference/code/

I found the mistake.

The change I will make now is that if you got code on the same line as the `-` 

``` jade
- if ($something)
```

will not start a code block, while

``` jade
-
    if ($something)
```

will do.

There's no other way to check if the following text is code or jade in another way.

This should also reflect the official engine.

It allows

``` jade
- if ($something):
    p Do something
- endif;
```

as well as

``` jade
-
    $someArray = ["some", "random",
         "values", "i", "just"
    "thought", "of"];
```

**Comment by jacmoe** [comment]
Awesome! :)

**Comment by TorbenKoehn** [comment]
Didn't mean to close this, first tell me: Is this fixed for you as well?

It passed all tests.

What I did now is splitting "expressions" (= or !=) and "code" (-)

Code will check if it has direct text, if it does, it will just stay on a single line and close the brackets directly after.

If there's no text on the same line, it will start a Text-Block, where all nodes a level deeper will get into the whole code block.

**Comment by jacmoe** [comment]
It actually worked better before the latest commit.
This was treated as one line before:

``` php
        -$menuItems[] = ['label' => 'Logout (' . Yii::$app->user->identity->username . ')',
          'url' => ['/site/logout'],'linkOptions' =>['data-method' => 'post']]
```

Now it fails.
The same applies to unbuffered.

``` php
      !=Nav::widget(['options' => ['class' => 'navbar-nav navbar-right'],
          'items' => $menuItems,])
```

What works now is code blocks:

``` php
      -
        NavBar::begin(['brandLabel' => 'Bugitor', 
        'brandUrl' => Yii::$app->homeUrl, 'options' => 
        ['class' => 'navbar-inverse navbar-fixed-top',],])
```

To be honest, I think it worked better before the latest commit.
If we accept that, currently, there is no optional leading dash for conditionals, and that - for some reason - we can't multi-line immediately before an 'else'.
This is fixing one thing and breaking several others.
Odd that your tests are not picking that up. :)

I am not meaning to complain, but I think I'll go back to 1.1.0, for now.

I will see if I can make a stand-alone test case.

**Comment by jacmoe** [comment]
Could Tale Jade not just eat the dash if it encounters one before a conditional?
I think it is inconsistent that one need to change the syntax when switching from one or the other.
Or am I wrong?

**Comment by jacmoe** [comment]
I am curious how MtHaml handles this..

**Comment by TorbenKoehn** [comment]
The 1.1.1 version now correctly mimics the behaviour of the official Node.js engine (You can always check it with the live-compiler at http://jade-lang.com)

Notice that it can't handle your first two cases as well

The first example should be written in one line or like this:

``` jade
-
    $menuItems[] = ['label' => 'Logout (' . Yii::$app->user->identity->username . ')',
        'url' => ['/site/logout'],'linkOptions' =>['data-method' => 'post']]
```

The second example could be replaced with multiple possibilities

``` jade
- 
    $widgetArgs = ['options' => ['class' => 'navbar-nav navbar-right'],
          'items' => $menuItems,]
!=Nav::widget($widgetArgs)
```

put it in one line, build the array before `->render()` and pass it as an argument etc.

The dash for conditionals is not actually _optional_, these are two different constructs

``` jade
if $something
    p Do something
else
    p Do something else
```

Notice that it doesn't have to be terminated, other than

``` jade
- if ($something):
    p Do something
- else:
   p Do something else
- endif;
```

This actually just puts `<?php ?>` tags around the dash-prefixed-line

What features are you lacking in the un-prefixed conditions? Maybe we could attack that part.

I think it's better to mimic the official behaviour
Jade works based on indentation, not (many) prefixes :)

Thoughts on this?

**Comment by jacmoe** [comment]
I've looked into how MtHaml handles it, and it merges multi-line before generating the php code.

I just checked what you can and cannot do in the Jade demo, and I stand corrected. :)
Perhaps Haml is more forgiving.
My bad.

Ok, then this is actually an improvement. In that it moves closer to how "real" Jade does it.
I will upgrade to the latest edition of TJ, then.
And get used to it.

And, yes: I think it is better to mimic the official behavior. :)

**Comment by jacmoe** [comment]
Just want to say that I am actually happy with this :)
Thanks for fixing it!
