### ISSUE TITLE
Buffered code blocks

### ISSUE THREAD

**Issue by jacmoe** [Talesoft/tale-jade#20]
It would be incredible useful to have support for buffered code blocks, because PHP code is so messy. :)

I have to resort to this hack when dealing with a buffered object:

``` jade
  -
    $columns = ['id','tracker_id', 'project_id', 'subject',
    'description:ntext', 'issue_category_id', 'user_id', ['class' => 'yii\\grid\\ActionColumn',
     'contentOptions' => ['nowrap'=>'nowrap'] ] ]

  !=GridView::widget(['dataProvider'=> $dataProvider,'filterModel'=> $searchModel,'columns'=> $columns])
```

**Comment by jacmoe** [comment]
Yes, I can probably include php, like:

``` jade
include:php includes/some-php
```

However, since I am writing a CRUD generator for Yii2 framework, I have to fit it into the template directly.

**Comment by TorbenKoehn** [comment]
The `include`-construct there actually doesn't compile to `include('...')`, it takes the content of the included file and puts it into proper PHP tags, so you don't need the `includes/some-php` file anymore after compiling once.

Assuming `includes/some-php.php` contains

``` php
<?php

$columns = ['id','tracker_id', 'project_id', 'subject',
    'description:ntext', 'issue_category_id', 'user_id', ['class' => 'yii\\grid\\ActionColumn',
     'contentOptions' => ['nowrap'=>'nowrap'] ] ];
```

Tale Jade will compile that to

``` php
<?php $columns = ['id','tracker_id', 'project_id', 'subject',
    'description:ntext', 'issue_category_id', 'user_id', ['class' => 'yii\\grid\\ActionColumn',
     'contentOptions' => ['nowrap'=>'nowrap'] ] ];
?>
```

directly, not to `include('includes/some-php.php')`

With that amount of options you'd get into trouble in almost any template language I guess.

Another possibility would be passing that stuff to the renderer, from PHP

``` jade
$renderer->render('jade-file', ['columns' => ['id', 'tracker_id', ...]]);
```

and using it directly inside the template then (`$columns` will be available this way).

That way you could also provide configuration outside of templates (e.g. client can select which columns to display)

Another thing I could think of would be that maybe we can shorten the style of "defining an associative array" a bit, maybe something like this:

``` jade
$options(class='yii\grid\ActionColumn', contentOptions=['nowrap' => 'nowrap'])
$columns('id', 'tracker_id', 'project_id', 'subject', ..., $options)
```

This would be Tale Jade exclusive, but we could actually implement something like this, $ isn't used anywhere in Node.js jade.

**Comment by jacmoe** [comment]
Yes, but Yii already passes $dataProvider and  $searchModel, etc. into the view.

It is the widget configuration array that can get unyieldingly long to be written out all in one line, hence the hack.
And because the crud generator I am writing now (for Yii) is somewhat restrictive because it has to fit into the architecture.
In my own code, I can go nuts..

If that associative array functionality doesn't allow us to break up the line(s), then it not especially useful since we can use unbuffered code for that.

**Comment by TorbenKoehn** [comment]
It would.

Attribute blocks are the only nodes that can be split across lines
You could actually write

``` jade

$options(
    class='yii\grid\ActionColumn',
    contentOptions=['nowrap' => 'nowrap']
)

$columns(
    'id',
    'tracker_id',
    'project_id',
    ...,
    $options
)
```

What do you think about it?
I actually think this would be a useful construct.

**Comment by jacmoe** [comment]
That would be really useful !  :+1: 
It would make the views so much cleaner, at least for Yii widgets..

Btw, my two Tale Jade powered Yii-2 extensions:
https://bitbucket.org/jacmoe/yii2-tale-jade
https://bitbucket.org/jacmoe/yii2-gii-jade

**Comment by TorbenKoehn** [comment]
Alright, then this is a feature proposal!

I'll think about how to implement this in a clean manner and get working on it.

I'll soon push some more bug-fixes and more tests I've been working on.

**Comment by TorbenKoehn** [comment]
It's in now, can you test it?

The variable assigning has a shitload of functionality, I need to document it somewhere

You can either assign like you do with normal tags, e.g.

``` jade

$greeting= 'Hello, my friend!'

p My greeting to you is: #{$greeting}
```

you can print variables without any =/- stuff

```

p
    $greeting
```

You can create Arrays with attribute blocks or normal assignments
Attribute blocks will try to merge the array with existing arrays of the same name

``` jade

$arr = ['a' => 1, 'b' => 2, 'c' => 3];

$arr(a=4, b=6)

// $arr will be ['a' => 4, 'b' => 6, 'c' => 3]

```

You can span the attribute block over multiple lines with whatever indentation you like

``` jade
$options(
    class='yii\grid\ActionColumn',
    contentOptions=['nowrap' => 'nowrap']
)

$columns(
    'id',
    'tracker_id',
    'project_id',
    ...,
    $options
)
```

should create your array correctly.

If you notice any bugs, tell me :)

**Comment by jacmoe** [comment]
Great stuff! :)
I will take it for a spin. :8ball:

**Comment by jacmoe** [comment]
Hmm..
This is the output:

```
 Columnus
Array ( [0] => ["class" => "yii\grid\SerialColumn"] [1] => id [2] => username [3] => auth_key [4] => password_hash [5] => password_reset_token [6] => ["class" => "yii\grid\ActionColumn"] )

Coluumns
Array ( [0] => Array ( [class] => yii\grid\SerialColumn ) [1] => id [2] => username [3] => auth_key [4] => password_hash [5] => password_reset_token [6] => Array ( [class] => yii\grid\ActionColumn ) )

Columns
Array ( [0] => Array ( [class] => yii\grid\SerialColumn ) [1] => id [2] => username [3] => auth_key [4] => password_hash [5] => password_reset_token [6] => Array ( [class] => yii\grid\ActionColumn ) ) 
```

**Comment by jacmoe** [comment]
From this:

``` php
    h3 Columnus
    $columnus(
      ["class" => "yii\grid\SerialColumn"],
      'id',
      'username',
      'auth_key',
      'password_hash',
      'password_reset_token',
      ["class" => "yii\grid\ActionColumn"])

    -print_r($columnus)
    br
    br

    h3 Coluumns
    $coluumns = [['class' => 'yii\grid\SerialColumn'],'id','username','auth_key','password_hash','password_reset_token',['class' => 'yii\grid\ActionColumn'],]

    -print_r($coluumns)
    br
    br




  -
    $columns = [
    ['class' => 'yii\grid\SerialColumn'],
    'id',
    'username',
    'auth_key',
    'password_hash',
    'password_reset_token',
    //'email:email',
    //'status',
    //'created_at',
    //'updated_at',
    ['class' => 'yii\grid\ActionColumn'],
    ]

  h3 Columns
  -print_r($columns)
  br
  br
```

**Comment by jacmoe** [comment]
I had to remove the commented out entries because the new code block doesn't take that into account.
It looks like strings are handled differently in the TJ code blocks?

**Comment by TorbenKoehn** [comment]
Can you tell me where exactly the problem in the output is?

I will fix it as soon as possible :)

**Comment by jacmoe** [comment]
'Columnus' is different from the two others.
print_r prints the quotes and that creates a problem when passing the object as an array argument.
Something is not quite as it should be I think.
The point is that all three arrays should be the same.

**Comment by TorbenKoehn** [comment]
Now I see the problem and I even know where exactly it is.

I will fix it as soon as I get to it and update this thread then :)

**Comment by TorbenKoehn** [comment]
I improved the expression handling in 1.2.1 now.

Please tell me if it works :)

**Comment by jacmoe** [comment]
It does work - nice job :100: 

I think I can safely close this issue.

Commenting out works, all three columns that I mentioned above prints the same, and for loops are really cool.

_closing_

**Comment by jacmoe** [comment]
Houston, we have a problem :)

I have this markup:

``` php
!=$view->render('_search', ['model' => $searchModel])
```

Tale Jade gives me a Jade error:

> Failed to parse jade: You should indent in by one level only

It actually does not matter what indentation I use..
Even if I don't indent at all.
Buffered / unbuffered - it does not matter.

When I do this:

``` php
$view->render('_search', ['model' => $searchModel])
```

I get this output:

``` php
<?php >render('_search', ['model' => $searchModel])?>
```

Somehow Tale Jade is now doing some uspeakable things to my view variable :x

**Comment by jacmoe** [comment]
I am opening a new issue for this.
