### ISSUE TITLE
Variables handling goes wrong

### ISSUE THREAD

**Issue by jacmoe** [Talesoft/tale-jade#25]
Houston, we have a problem :)

I have this markup:

!=$view->render('_search', ['model' => $searchModel])

Tale Jade gives me a Jade error:

```
Failed to parse jade: You should indent in by one level only
```

It actually does not matter what indentation I use..
Even if I don't indent at all.
Buffered / unbuffered - it does not matter.

When I do this:

$view->render('_search', ['model' => $searchModel])

I get this output:

<?php >render('_search', ['model' => $searchModel])?>

Somehow Tale Jade is now doing some uspeakable things to my view variable :x

**Comment by jacmoe** [comment]
D'oh - the error was in between my ears :dancers: 

Closing :octopus:

**Comment by TorbenKoehn** [comment]
Hello!

I just created a test for it (https://github.com/Talesoft/tale-jade/blob/dev-master/Test/ExpressionAndCodeTest.php#L63)
The test passes for me, it compiles correctly.

Can you send me a greater part of the file you're parsing around the part where the error occurs?
I think it's an indentation problem of any kind.

**Comment by TorbenKoehn** [comment]
Lol, tell me what happened haha

**Comment by jacmoe** [comment]
Torben, I totally forgot to check _search.jade :D
Sorry about that.
There was indeed indentation issues.

[edit]
And that fixed it
[/edit]

**Comment by TorbenKoehn** [comment]
Yeah, but that's important!

Obviously it seems to be hard to find errors in files you've rendered yourself _inside_ another template, I will think about adding the file-name (if available) to the error messages :)

**Comment by jacmoe** [comment]
Yes it is challenging to debug.
I like that there is compiled php code to look at most of the time.
It could be better.
