### ISSUE TITLE
Allow interpolation for any valid php expression

### ISSUE THREAD

**Issue by elquimista** [Talesoft/tale-jade#36]
For now, interpolation works for php variables only. Original Jade language supports any JavaScript expression for interpolation.
I tried to interpolate php function inside string and it threw an error.
When I look at in the .phtml file, function expression is wrapped inside isset() function, which is causing the error.
Can we make this quick?

**Comment by TorbenKoehn** [comment]
I will take a look at this ASAP.

**Comment by TorbenKoehn** [comment]
It's in now, could you test it?

Almost any kind of PHP expression should be supported this way.

**Comment by elquimista** [comment]
Hey Torben, thanks for solving the issue.

**Comment by elquimista** [comment]
When are you going to release a new version reflecting this interpolation stuff update?

**Comment by TorbenKoehn** [comment]
I did! 1.3.3 is the new one.

**Comment by elquimista** [comment]
great!
