### ISSUE TITLE
Improve pretty option's functionality

### ISSUE THREAD

**Issue by elquimista** [Talesoft/tale-jade#40]
Setting `pretty` to `true` outputs html code that's better than `pretty = false` for legibility.
But it still looks a bit messy to me, in terms of indentation etc.
Can you make it improve the output in a more precise and beautified way?
Thanks in advance.

**Comment by TorbenKoehn** [comment]
Can you tell me where exactly? :)

**Comment by elquimista** [comment]
When you check view source of the result in ff / chrome, you'll see opening and closing tags are not indented in a pretty manner.
It's not a big problem, maybe I'm too obsessed with this. But it'd be great if you follow me and solve this issue.

**Comment by CagatayUlubay** [comment]
I still don't understand what do you mean. Can you give us examples?

Following is how `pretty => true` looks for me and it's looking allright for me:

![Tale Jade Source pretty output](http://i.imgur.com/Yd9FZLD.png)

Following the `pretty => false` output:

![Tale Jade Source unpretty output](http://i.imgur.com/YLO8csP.png)

**Comment by elquimista** [comment]
sorry guys. I thought it wrong. I'm closing this issue.

**Comment by TorbenKoehn** [comment]
That's no problem my friend, please tell us whenever you see a problem with the pretty-option and where exactly, we will fix it :)

**Comment by elquimista** [comment]
Now I have another question. I tried to place php function as a mixin parameter. It didn't work well except the following way.

`+button_with_preloader(!__('Submit'))#btn_submit_feedback`

Now I can use php functions as a mixin param, but the way it works is inconsistent with interpolation usage. I think it should be either `#{__('Submit')}` or `!{__('Submit')}`

What do you think?

**Comment by TorbenKoehn** [comment]
This seems to be a problem in attribute parsing.

I'll open a new issue and take a look at it.
