### ISSUE TITLE
Using text block (.) inside an if makes if swallow everything ahead

### ISSUE THREAD

**Issue by svallory** [Talesoft/tale-jade#42]
**Example:**

```
  if ($noscript)
    script.
      // The next p shouldn't be inside this if

  p
```

**output:**

```
<?php if (isset($noscript) ? $noscript : false) {?>
  <script>
    // The next p shouldn't be inside this if
  </script>
  <p></p>
<?php }?>
```

**Comment by elquimista** [comment]
This is surely a problem. Just confirmed it on Tale Jade Sandbox.

**Comment by TorbenKoehn** [comment]
This is indeed a huge problem.

I'll take a look at it right away.

**Comment by TorbenKoehn** [comment]
As a quick workaround, it seems this one:
http://sandbox.jade.talesoft.io/id-5698348a1961d.html
seems to parse correctly.

This one
http://sandbox.jade.talesoft.io/id-5698352a98568.html
doesn't.

I'm on it.

~~Edit: Also noticed that the live compiler could need a fucking `save`-function.~~

**Comment by TorbenKoehn** [comment]
Can you check if this has been fixed for you?

**Comment by elquimista** [comment]
Seems this issue is fixed now.

**Comment by svallory** [comment]
It works! :)

**Comment by TorbenKoehn** [comment]
Awesome! Thanks for your feedback :)
