### ISSUE TITLE
Another issue with latest version (v1.3.4)

### ISSUE THREAD

**Issue by elquimista** [Talesoft/tale-jade#48]
This issue is related to `include` statement.

mixin.jade

``` jade
h2 Hello
```

1.jade

``` jade
include mixin.jade
```

After compilation, it should generate only 1.html with the following contents:

``` html
<h2>Hello</h2>
```

But the result is it generates 1.html as well as mixin.html. And the contents are not good.
mixin.html

``` html
<h2>Hello</h2>
```

1.html

``` jade
h2 Hello
```

This is certainly a bug right?

**Comment by TorbenKoehn** [comment]
I'll check that right now

**Comment by elquimista** [comment]
I came to find out this issue when I was getting an error which didn't use to occur before upgrading to v1.3.4. (I was using v1.3.1)
Here's my jade code:
../Mixin/button_with_preloader.ctp.jade

``` jade
mixin button_with_preloader(title)
    button= $title
```

view.ctp.jade

``` jade
include ../Mixin/button_with_preloader.ctp.jade
...
+button_with_preloader(__('Submit'))#btn_submit_feedback.right._no-margin-bottom
```

`include` and using mixin `+button_with_preloader` was working fine with v1.3.1, but with 1.3.4, it throws an error saying:
`Failed to compile Jade: Mixin button_with_preloader is not defined (mixinCall at 33:34)`

**Comment by TorbenKoehn** [comment]
Yes, that's a bug indeed.

I've added a test for your first code snippets in this thread, these pass (Look at the dev-master branch)

The second thing you posted is a bug, I'm fixing it right now.

**Comment by elquimista** [comment]
Yeah, the first snippet works fine. I wonder why it wasn't working before.
And the second snippet, I tried a simpler test:

mixin.jade

``` jade
mixin button(title)
    button= $title
```

1.jade

``` jade
include mixin
+button('Go')
```

The above code works without any issue. But it throws an error if I change `include mixin` to `include mixin.jade`

**Comment by TorbenKoehn** [comment]
Please update and tell me if this is fixed for you

**Comment by elquimista** [comment]
Thanks, it's working now. But I have another issue again.
This code used to be working with earlier version (e.g. 1.3.1)

``` jade
div(id!='clip_#{$clip->id}')
```

Now it doesn't work, throwing an error: `Failed to compile Jade: Failed to lex jade: Unclosed attribute block`.

If I remove `!` in the attribute assignment expression, the error doesn't show up, but instead if I inspect the html page in browser, I get `<div id="clip_<?=htmlentities(isset($clip->id) ? $clip->id : '', \ENT_QUOTES, 'UTF-8')?>"></div>`, which I expected to be `<div id="clip_1"></div>`.

Please check this and let me know.

**Comment by TorbenKoehn** [comment]
Nooo, I broke attribute escaping.

Sorry haha, I'll fix this quickly.

**Comment by TorbenKoehn** [comment]
Can you test this again as well? Don't forget to update to 1.3.6

**Comment by elquimista** [comment]
It works. thanks :+1:
