### ISSUE TITLE
_options ?

### ISSUE THREAD

**Issue by jacmoe** [Talesoft/tale-jade#64]
I am using 1.4.0 and it looks like Compiler, Lexer, Parser and Renderer still uses the `$_options` variable instead of `$options`.

I fixed it by doing a simple search and replace.

The old Configuration class used `$_options` but the tale-config package uses `$options`.

I could issue a PR, but I thought I'd check in and see why other people are not getting this error.

**Comment by TorbenKoehn** [comment]
Yep, that was my error when I changed the tale-config api yesterday.

I will merge a hotfix for master in a few minutes.

**Comment by TorbenKoehn** [comment]
Can you test it now?

What needs to happen is that tale-jade uses tale-config 0.1, not 0.2.
You might need to re-install tale-jade and tale-config (just delete `vendor/talesoft` and `composer.lock` and run `composer update`)

I re-created the 0.1 with the new changes yesterday when I realized that tale-jade needs 0.1 right now.
I updated the code style conventions to PSR-2 (no _ before privates)
The PSR-2 version of tale-config is 0.2 now.

**Comment by jacmoe** [comment]
Fixed - thanks! :+1: 

I don't think that tag `0.4.0.1` is kosher with Composer, so I just use `dev-master`for tale-jade now. :)

**Comment by TorbenKoehn** [comment]
Yup, seems like it.

It's 1.4.1 now, the next version will be 1.5 and will be released in a few days.

It's a full overhaul.

**Comment by jacmoe** [comment]
> It's a full overhaul.

You are busy :+1: 

Looking forward to it!
