### ISSUE TITLE
Itemscope itemtype error

### ISSUE THREAD

**Issue by jacmoe** [Talesoft/tale-jade#66]
With this:

```
.blogentry(itemscope itemtype="http://schema.org/BlogPosting")
```

I get this:

> Failed to lex jade: Unclosed attribute block (Line: 2, Offset: 21)

Any pointers?

**Comment by jacmoe** [comment]
So, I tried this:

```
.blogentry(itemscope="itemscope" itemtype="http://schema.org/BlogPosting")
```

And the error goes away, but it renders like this:

```
<div class="blogentry" itemscope="itemscope" itemtype="http://schema.org/BlogPosting"></div>
```

I suspect that Jade will render it correctly by default, from reading this SO post:
http://stackoverflow.com/questions/11020142/jade-element-attributes-without-value

Edit:  
And it does indeed.

I tried to enter the original line into the Jade online demo, and it does the right thing.

```
<div class="blogentry" itemscope itemtype="http://schema.org/BlogPosting"></div>
```

So, I think that Tale Jade should handle a line like this:

```
.blogentry(itemscope itemtype="http://schema.org/BlogPosting")
```

**Comment by TorbenKoehn** [comment]
This should be fixed with the new lexer scanners and [re-written scanning algorithms](https://github.com/Talesoft/tale-jade/blob/compiler-enhancements/Jade/Lexer/Scanner/AttributeScanner.php#L39) that work more consistent and stable.

I'll get the update up as soon as possible.

**Comment by TorbenKoehn** [comment]
Checked it again.

This is a bug.
http://sandbox.jade.talesoft.io/id-56e159b37bbbb.html

Without a `,`, it won't even render correctly.

As said above, I've completely re-written attribute parsing in the new branches.
I'll try to get the update up today, I don't know if I make it (Compiler still needs a lot of work)

**Comment by jacmoe** [comment]
Take your time :+1: 

I am not in dire need.  
Looking forward to it, though. :)

**Comment by TorbenKoehn** [comment]
Well, you can always get around it by using plain HTML :)

Any line starting with `<` is handled as plain HTML by Tale Jade (and official Jade)!

**Comment by jacmoe** [comment]
> Well, you can always get around it by using plain HTML :)

That is too easy @TorbenKoehn :)

But thanks for reminding me - I was not aware of that :+1:

**Comment by TorbenKoehn** [comment]
Some love for you, my friend. Can you test it?

**Comment by jacmoe** [comment]
It works wonderfully! Thanks :+1:
