### ISSUE TITLE
The passed adapter doesn't exist

### ISSUE THREAD

**Issue by vanrez-nez** [Talesoft/tale-jade#68]
I'm trying to run the latest version (with tails 0.1) but when I run the sample code I get an error on file: /tale-jade/Renderer.php  -> The passed adapter doesn't exist. Any ideas?

**Comment by TorbenKoehn** [comment]
Can you give me the exact code you used to run the Renderer?

**Comment by TorbenKoehn** [comment]
Any update on this?

**Comment by TorbenKoehn** [comment]
Can you give me a reply on this? I'll close it soon if no feedback appears.
