### ISSUE TITLE
Variables cause parse error

### ISSUE THREAD

**Issue by ianmaddox** [Talesoft/tale-jade#73]
The following code causes a fatal:

```
extends layout

block vars
  - var title="Hello World"
  - var username=""

block content
  .homepage
    #main.top-content
```

The error:

```
<br />
<b>Parse error</b>:  syntax error, unexpected 'var' (T_VAR) in <b>/...../main.phtml</b> on line <b>1</b><br />
```

Using latest release of tale-jade, PHP 5.6.18, Apache

**Comment by CagatayUlubay** [comment]
Try removing the "var" infront of the vars.

Look how it's done here: http://sandbox.jade.talesoft.io/index.php?example=code

**Comment by TorbenKoehn** [comment]
This is not JavaScript :)

To declare a variable you use

``` jade
- $title = "Hello World"
- $username = ''
```

or the (Tale Jade exclusive) variable notation

``` jade

$title = "Hello World"
$username = ""

h1= $title
p Welcome #{$username}
```

**Comment by TorbenKoehn** [comment]
Is this problem solved for you?

**Comment by TorbenKoehn** [comment]
I take this as solved. Thank you for using Tale Jade :)
