### ISSUE TITLE
Interpolation in elements attributes

### ISSUE THREAD

**Issue by a-guerrero** [Talesoft/tale-jade#74]
Hi, I'm trying to use interpolation in elements attributes like this (the code is just and example to demonstrate the error):

``` jade
$dir= "http://my-site/content"
//- Works fine
p #{$dir}/assets
//- Don't work
img(src="#{$dir}/assets")
```

Output:

``` html
<p>http://my-site/content/assets</p>
<img src="<?=htmlentities(isset($dir) ? $dir : '', \ENT_QUOTES, 'UTF-8')?>/assets">
```

I had to play with the variable to make it work, but it would be nice to have interpolation in elements attributes just like the original implementation :-)

``` jade
$dir= "http://my-site/content"
$dir= "{$dir}/assets"

//- Works fine
p #{$dir}
//- Works fine
img(src=$dir)
```

**Comment by zorca** [comment]
You may use [Attribute Stacking](http://sandbox.jade.talesoft.io/index.php?example=attribute-stacking):

```
$dir= "http://my-site/content"
img(src=$dir, src="/assets")
```

or simple PHP syntax:

```
$dir= "http://my-site/content"
img(src=$dir."/assets")
```

But [original Jade Compiler works with vars without specific syntax](http://jade-lang.com/reference/interpolation/): :-(

```
- var dir= "http://my-site/content"
img(src=dir + "/assets")
```

With this code I have error:

```
Uncaught exception 'Tale\Jade\Compiler\Exception' with message 'Failed to compile Jade: Failed to parse Jade: Attributes in elements and mixins need a name
(attribute at 8:20)
```

**Comment by TorbenKoehn** [comment]
``` jade

$dir = "http://my-site/content"
img(src=$dir."/assets")

//or

$dir = "http://my-site/content"
img(src!="#{$dir}/assets")
```

http://sandbox.jade.talesoft.io/id-56fd4487857ff.html

Notice the `!=` instead of `=` at the attribute to avoid value escaping (Tale Jade escapes **everything** by default for security reasons)

Always remember that this is Jade made for PHP, not just a simple fork and syntax change :)

Please tell me if this is resolved for you.

**Comment by a-guerrero** [comment]
Thanks!, both solutions work great for me! :grin:.
