### ISSUE TITLE
support comment // if IE 8?

### ISSUE THREAD

**Issue by DavidKk** [Talesoft/tale-jade#75]
it only compile to  not

**Comment by TorbenKoehn** [comment]
Generally, yes, you are right.

But you don't use `//`-style-comments for IE-conditionals, you use the fact that Tale Jade also handles normal HTML markup (When the line starts with `<`, it's handled as plain-text)

Watch this:
http://sandbox.jade.talesoft.io/id-57060fbfe2450.html

There is an error, though, the ![endif] gets handled as interpolation. 
I thought I fixed it but I did it wrong. I already made it not interpolating it, but it forgets the `![]` :D 

I will bring up a hotfix soon.

**Comment by TorbenKoehn** [comment]
This should be fixed with 1.4.2

Can you test it and give me feedback?

**Comment by TorbenKoehn** [comment]
The tests say it works, please re-open this if it doesn't :)
