### ISSUE TITLE
Need help creating documentation!

### ISSUE THREAD

**Issue by TorbenKoehn** [Talesoft/tale-jade#83]
I really need help creating more documentation resources.

If anyone is willing to help, I'd provide everything needed including an information channel that knows all deep secrets of Jade (me).

What I need exactly is:
1. PHP Doc Blocks in the 1.5 and 1.6 branches (_many_ doc blocks...)
2. A real (possibly Jade&Bootstrap powered) Open Source website that will be hosted at http://jade.talesoft.io containing
    - The [sandbox](http://jade.talesoft.io) (Might also be re-written)
    - Installation and usage guides
    - A list of all common features of Tale Jade
    - A list of advanced techniques with Tale Jade (There are quite a few, I just forget them when I try to write them down)
    - A developer's guide for extending Tale Jade (Necessary after 1.5)
3. Maybe a new README that is cleaner to read and references the website correctly
4. Maybe, just maybe, a really cool and actually working phpdoc-template.
5. A logo! (Maybe with a neat Jade-stone or something like that)

Any help is appreciated

**Comment by zorca** [comment]
What about VPS-hosting with all PHP-versions and MySQL? I can give you the VPS-server free of charge installation (Moscow location) of WordPress and multilingual support.

**Comment by TorbenKoehn** [comment]
That is not the problem, I have the domains already, I have a web-space already, with all recent PHP versions I can test on. I primarily need the content :)

I even [have a website](http://jade.talesoft.io) on it already, but it's just the README converted via ghpages.

But thanks for your offer, I really appreciate it!

**Comment by zorca** [comment]
Sorry, I didn't understand you right. )))

**Comment by TorbenKoehn** [comment]
Nothing to apologize for, you made a great offer :)

**Comment by zorca** [comment]
OK, I can help with documentation, if you give me rights to its completion. I know very well the original Jade and Tale-Jade too ( :-) ).

**Comment by TorbenKoehn** [comment]
Tell me what you need and I'll provide it.

As for the jade.talesoft.io website, I didn't even start.

I guess the best would be a small Symfony2 application, I guess I'll start coding it today, publish it and then grant access to people that want to help (including you!)

Thank you a lot :)

**Comment by zorca** [comment]
I know a very good CMS for such purposes: Dokuwiki. 
It works perfectly and supports pages revisions, simple markdown syntax too.

**Comment by TorbenKoehn** [comment]
DokuWiki seems to be pretty neat. I'll check it out, thanks :)

**Comment by TorbenKoehn** [comment]
Edited again, I also need a logo :)

**Comment by zorca** [comment]
And by the way, did you know that original Jade was renamed to Pug??? ) I really hope that Tale-Jade not change the name or get your own name and logo.

**Comment by TorbenKoehn** [comment]
I always thought that it was named Pug first and was then changed to Jade.
https://github.com/pugjs/pug/issues/2184

Appearently there is a company that has a trademark on the name Jade.

I guess I probably _have_ to change it.

So...any ideas? :D

**Comment by zorca** [comment]
Fresh install of Docuwiki with my favorite template: http://jade.steelcat.org

**Comment by TorbenKoehn** [comment]
Yeah, I've seen that template, it's pretty cool :)
I guess we will use this for starters, we can upgrade anytime later.

We should wait for the decision regarding the name change before we create new sub-domains

Thank you

**Comment by TorbenKoehn** [comment]
We focus our documentation resources on [Phug](https://github.com/phug-php), rather than Tale Jade now.
