### ISSUE TITLE
Alternative name

### ISSUE THREAD

**Issue by TorbenKoehn** [Talesoft/tale-jade#84]
We need a new name.

4 Characters maximum.

Can I have some input on this? Maybe even some name suggestions? 

Any idea or feedback is welcome :)

---

Current Name-Suggestions by probability that I'll take them:
- Chi (.chi, .jade, .jd)
- Shi (.shi, .jade, .jd)
- Inu (.inu, .jade, .jd)

---

**Update (15.12.2016):**

Tale Jade will be [Phug](https://github.com/phug-php) in the future, a collaboration project of currently existing Jade/Pug implementations

**Comment by zorca** [comment]
Jape = Jade + PHP

**Comment by TorbenKoehn** [comment]
Let's collect some, at the end I'll make a poll and see if I can get a few votes on it.

What I thought of so far
- Maya
- Phug (See what I did there?)

My creativity is limited on fridays haha

Keep the suggestions coming

**Comment by zorca** [comment]
**Phade**

looks good

**Comment by TorbenKoehn** [comment]
[Phade](https://github.com/andreasnrb/phade) already exists I guess

Also, I'd prefer 4 chars :)

**Comment by dsifford** [comment]
@TorbenKoehn You might want to consider dropping the "Jade" name..

The nodejs "Jade" is now "Pug" --- They were forced to switch names for legal reasons.

**Comment by TorbenKoehn** [comment]
@dsifford Yes, but what name? I actually don't want to go with "Tale Pug" or something like that, since Tale Jade is pretty different from official Pug, it's just backwards compatible

**Comment by zorca** [comment]
What about **Jale** ??? I have not found the use of this name. 4 chars, a resemblance to Jade. Everything you wanted to. ) Or **Jape**, as suggested before.

**Comment by zorca** [comment]
And I think Phade is still the best name for the project, despite its use. https://github.com/andreasnrb/phade - last commit year ago. It's not so serious project. It's not on Packagist. 
Packagist does not contain any package with the same name.

**Comment by TorbenKoehn** [comment]
I don't like `Jale`, `Jape` or `Phade` because it's related to `Jade` and I don't want that.

I don't even want a relation to `Pug`, I rather want this to be a **Pug-_style_**, completely own and focused on PHP template engine with a completely own name. `Phug` would be the absolute limit of relation to `Pug`, but I'd rather like a new name with 2, 3 or 4 chars.

I didn't come up with a cool one yet, but I'll increase the speed of this process over this week so that we have our new name implemented at the end of this week.

Still open for suggestions :)

**Comment by zorca** [comment]
Pug-style names: Kai, Shi, Pumi, Ainu. Not similar to anything except dog breeds. :)

**Comment by TorbenKoehn** [comment]
Those are cooler, I like Shi and Ainu. Shi is my favorite.

Where do they come from?

**Comment by zorca** [comment]
Shi - short & simple, I like it.

**Comment by TorbenKoehn** [comment]
What would be the file extension? ".shi"?

**Comment by jaydenseric** [comment]
What about "Inu" (.inu), which means dog in Japanese. Like Shiba Inu: https://en.wikipedia.org/wiki/Shiba_Inu#Etymology. It's short and dog themed like Pug, with a potentially fun character.

**Comment by YamiOdymel** [comment]
+1 for Inu, sounds cute and meaningful, and the file extension is special too.

**Comment by debo** [comment]
My personal suggestion, considering also from where you are coming from with the project would be to go with the Phug option.

The reason is mostly because both Everzet and Kylekatarnls following the rename of the master project converged their efforts in a the new project [pug-php/pug](https://github.com/pug-php/pug) and also because the similarity with the original project will give you easier visibility and mnemonic recollection giving you some sort of free PR marketing.

The only small issue is that you can't go for phug/phug because phug is already taken but if you remain in the talesoft namespace then it's all good.

The point that I'm trying to make is that a name that will remind of the original will help mind association boosting the discovery and adoption of the project because people will likely search for pug for php and not shi for php.

My 2 cents

**Comment by jacmoe** [comment]
I like 'Inu' - and I really do not like 'Phug' because it sounds like 'fuck' and 'thug' (especially in a Russian accent :p )

To let people discover the library, simply put something about 'Pug' in the tagline.

Anyway, since this library is so cool, it will be adopted by people discovering it.

I think 'Inu' will help with that :)

Just my two cents.

**Comment by jacmoe** [comment]
> A complete and fully-functional implementation of the Pug template language for PHP

Since I reckon that tale-jade is already tagged with 'jade' at Packagist, I think discovery takes care of itself. Provided that the tag be changed to 'pug', of course (or simply added)

**Comment by TorbenKoehn** [comment]
Thank you for your input, @jacmoe, I appreciate it :)

Now, I have to admit something. Some weeks ago I contacted @kylekatarnls, the developer of the one other Pug implementation that is actually usable right now and we decided to cross beams and create a new, official implementation that aims to compete with template engines like Twig and Blade on a professional level.

We decided to call it `Phug`, despite the fact that it sounds like `Fuck`, since it's simply the closest association to Pug and PHP we can reach with the name and we're living in a world where `fuck` is consistent in the daily vocabulary of a developer anyways.

We have a GitHub org (http://github.com/phug-php), we have a packagist namespace (https://packagist.org/packages/phug/), we have a bunch of modules already finished or, at least, in development (https://github.com/phug-php), we have a domain (http://phug-lang.com, docs soon) and we have a real good concept.

If anyone wants to get involved, e-mail me (torben@talesoft.codes). You don't need to contribute code alone, anything that helps, helps (e.g. an own logo, website/docs designs, ideas for features, unit tests etc.)

**Comment by jacmoe** [comment]
I sincerely hope that phug-php will have the flexibility that tale-jade has, especially the ability to just include php and js files as-is, that is really flexible!
Godspeed with that. :)

**Comment by TorbenKoehn** [comment]
@jacmoe It will, and it will be even more flexible.

We created a really nifty structure to allow extensions at any point, there will literally be a `Tale Jade` extension that configures Phug PHP to work exactly like Tale Jade did and every single feature can be turned on and off or be replaced completely.

Once we're done, I will deprecate Tale Jade and link this repository to the new Phug PHP implementation :)

**Comment by zorca** [comment]
Good news!

**Comment by debo** [comment]
@TorbenKoehn just one question, in the meanwhile, do you recommend we use tale-jade or https://github.com/pug-php/pug ?

**Comment by TorbenKoehn** [comment]
@debo PugPHP is pretty awesome, but Tale Jade offers some non-standard features that PugPHP does't have, I simply implemented these because I could. These features also get an own extension set in Phug, so you can simply do a drop-in replacement in the end. I'd recommend Tale Jade :)

**Comment by kylekatarnls** [comment]
Hi @debo, I did a lot of work on pug-php then I now work with @TorbenKoehn on phug-php, we're trying to take the best of both tale-jade and pug-php and we will try to provide easy way to migrate from the old projects to the new one. Meanwhile I would also recommend to stick to the project you're currently using because for both there will be breaking changes.

And if you start a project I recommend Tale Jade too as it would probably be a little closer to the future phug-php. And I recommend to use it in a "standard" way (I mean stay as close as possible to the pugjs syntax for tags, attributes, mixins, filters, etc.)

**Comment by kylekatarnls** [comment]
@debo If you want to participate in the project, please let us know.

**Comment by debo** [comment]
@TorbenKoehn @kylekatarnls thanks a lot for the advices, very appreciated. I would like to participate but I need to clear the backlog of my own [project](http://phansible.com/) before, I am so far behind with things, but I will definitely keep the offer in mind.

**Comment by jacmoe** [comment]
I haven't gotten a notice that this project has been superceded by the new project, so ...

I've checked Phug, but it does look pretty stale.

Is this the project to use, or should I switch to using tale-pug ?

Cheers! 😄

**Comment by kylekatarnls** [comment]
Hi, Phug is stable and pug-php already switch to use phug. Tale-pug (tale-jade) will also be refactored someday to use it. Right now, @TorbenKoehn is working on the new version of tale-pug that would use the new engine and keep the tale-pug specific features while I'm working on a common documentation for the 3 projects: https://phug.selfbuild.fr (temp preview until we finished it).

You can switch to phug, then when tale-pug 2 would be released it should be easy to reswitch to it.

**Comment by jacmoe** [comment]
Good  to know that Phug is happening!

I will probably take it for a spin, but since I am maintaining a Tale-jade wrapper for Yii, and a lot of projects based on it, I probably think it will be safer for me to migrate to Tale-pug.

**Comment by kylekatarnls** [comment]
Hi, it's very interesting. **pug-php** also has a Yii2 adapter but not yet compatible with **pug-php 3** and so **phug**. As you maintain a Yii adapter you may be interested by this proposition: https://github.com/jacmoe/yii2-tale-jade/issues/2
(I moved my message to not pollute this topic)

**Comment by kylekatarnls** [comment]
Hi, this is the new cross-engine adapter for Slim: https://github.com/pug-php/pug-yii2

Handle Phug, Tale-pug and Pug-php.

@jacmoe if you wont to contribute to it, do not hesitate.
