### ISSUE TITLE
Spaces in the end of lines

### ISSUE THREAD

**Issue by vr55** [Talesoft/tale-jade#88]
When i add space at the end of any keyword, i have failed to compile error.
For example:
hr<space>

**Comment by TorbenKoehn** [comment]
Yep, I noticed that one a whole ago already. I don't know exactly what's causing it, but I'll surely fix it very soon, I'll update this thread then.

**Comment by TorbenKoehn** [comment]
I removed automatic space-insertion in 83eee44f49ec0550cc2899b2dfb06a907e0b6ef5, I guess you can test it already, the release will come soon (I will implement some more fixes first)

**Comment by TorbenKoehn** [comment]
Hey there, current master has this fixed (will be 1.4.3 in a few minutes)

Can you test it?

**Comment by vr55** [comment]
Yes, I tested your fix already and everything is ok now. Thank you very much

Пользователь Torben Köhn notifications@github.com писал:
